#!/usr/bin/env python3
#
# Copyright (c) 2022, TU/e Robotics, Netherlands
# All rights reserved.
#
# \author Rein Appeldoorn


import os

import rospy

from challenge_clean_the_table.clean_the_table import setup_statemachine
from robot_smach_states.util import startup

if __name__ == '__main__':
    challenge_name = os.path.basename(__file__)
    rospy.init_node(challenge_name)
    startup(setup_statemachine, challenge_name=challenge_name)
