choice_answer_mapping = {
"Which German Count invented the zeppelin":"Count von Zeppelin",
"Who was the first president of the USA":"George Washington",
"What meat was reserved for the Emperor":"Pork",
"In which city was the Titanic built":"Belfast",
"How many children did Queen Victoria have":"Nine children",
"Which French king was called the Sun King":"Louis the forteenth",
"What was in England the northern frontier of the Roman Empire":"Hadrians wall",
"In which 1979 film was the spaceship called Nostromo":"Alien",
"Who was the first king of Belgium":"Leopold the first",
"What was the former name of New York":"New Amsterdam",
"What was the Latin name of Paris in Roman times":"Lutetia",
"Which city was the capital of Australia":"Melbourne",
"Give another name for the study of fossils":"Paleontology",
"What do dragonflies prefer to eat":"Mosquitoes",
"Which insects cannot fly but can jump higher":"Fleas",
"What is the name of the European Bison":"Wisent",
"What is called a fish with a snake like body":"Eel fish",
"Which plant does the Canadian flag contain":"Maple",
"Which is the largest species of the tiger":"Siberian tiger",
"Which malformation did Marilyn Monroe have when she was born":"Six toes",
"What is the house number of the Simpsons":"Number 742",
"What dog in ancient China was restricted to the aristocracy":"Pekinese",
"Who is the director of Reservoir Dogs":"Quentin Tarantino",
"What number is on Herbie the beatle":"Fifty three",
"Give the name of the best James Bond parody":"Austin Powers",
"What is the name of the bald commander of the Enterprise in Star Trek":"Captain Picard",
"Who was the leading actress in Sister act ":"Whoopi Goldberg",
"What is the country top level domain of Belgium":"The dot b e domain",
"Which unit is an indication for the sound quality":"Kbps",
"In computing what is Ram short for":"Random Access Memory",
"Who was the first man to fly around the earth":"Yuri Gagarin",
"On which hemisphere were the most dinosaur skeletons found":"The northern hemisphere",
"What color is cobalt":"Blue",
"Who invented vulcanized rubber":"Goodyear",
"Which device do we use to look at the stars":"Telescope",
"Which unit indicates the light intensity":"Candela",
"Who invented the barometer":"Torricelli",
"Who was the first American in space":"Alan Shepard",
"Two brothers invented the hot air balloon. What was their surname":"Montgolfier",
"Who was the inventor of the steam engine":"James Watt",
"Which device was invented by Henry Mill":"The typewriter",
"What is the lightest existing metal":"Aluminium",
"What are the three primary colors":"Blue yellow and red",
"Which planet is nearest":"Mercury",
"How long is the Great Wall of China":"6259 kilometers",
"What is the largest number of five digits":"99999",
"What is the most fractured human bone":"Clavicle",
"Which South American country is named after Venice":"Venezuela",
"How many stars feature on the flag of New Zealand":"Four stars",
"What colour do you get when you mix red and white":"Pink",
}

spec = '<question>'
choices = {'question': [k for k, v in choice_answer_mapping.items()]}

