#! /usr/bin/env python3

import rospy
from robot_smach_states.util.startup import startup
from challenge_carry_my_luggage.carry_my_luggage import CarryMyLuggage

if __name__ == "__main__":

    rospy.init_node('state_machine')

    startup(CarryMyLuggage)
