#! /usr/bin/env python3

import rospy
from robot_smach_states.util.startup import startup
from challenge_move_obstacles import MoveObstacles


if __name__ == "__main__":
    rospy.init_node('challenge_move_obstacles')

    startup(MoveObstacles)
