#!/usr/bin/python

# ROS
import rospy

# TU/e Robotics
from robot_smach_states.util.startup import startup
# Challenge example
from challenge_take_out_the_garbage.take_out_the_garbage import TakeOutGarbage

if __name__ == "__main__":
    rospy.init_node('take_out_the_garbage')
    startup(TakeOutGarbage)
