choice_answer_mapping = {
    "Who are the inventors of the C programming language?":"Ken Thompson and Dennis Ritchie ",
    "Who is the inventor of the Python programming language?":"Guido van Rossum",
    "Which robot was the star in the movie Wall-E?":"Wall-E",
    "Where does the term computer bug come from?":"From a moth trapped in a relay",
    "What is the name of the round robot in the new Star Wars movie?":"BB-8",
    "How many curry sausages are eaten in Germany each year?":"About 800 million currywurst every year",
    "Who is president of the galaxy in The Hitchhiker's Guide to the Galaxy?":"Zaphod Beeblebrox",
    "Which robot is the love interest in Wall-E?":"EVE",
    "Which company makes ASIMO?":"Honda",
    "What company makes Big Dog?":"Boston Dynamics",
    "What is the funny clumsy character of the Star Wars prequels?":"Jar-Jar Binks",
    "How many people live in the Germany?":"A little over 80 million",
    "What are the colours of the German flag?":"Black red and yellow",
    "What city is the capital of the Germany?":"Berlin",
    "How many arms do you have?":"two",
    "What is the heaviest element?":"Plutonium when measured by the mass of the element but Osmium is densest",
    "What did Alan Turing create?":"Many things like Turing machines and the Turing test",
    "Who is the helicopter pilot in the A-Team?":"Captain Howling Mad Murdock",
    "What Apollo was the last to land on the moon?":"Apollo 17",
    "Who was the last man to step on the moon?":"Gene Cernan",
    "In which county is the play of Hamlet set?":"Denmark",
    "What are names of Donald Duck's nephews?":"Huey Dewey and Louie Duck",
    "How many metres are in a mile?":"About 1609 metres",
    "Name a dragon in The Lord of the Rings?":"Smaug",
    "Who is the Chancellor of Germany?":"Angela Merkel",
    "Who developed the first industrial robot?":"The American physicist Joseph Engelberg. He is also considered the father of robotics.",
    "What's the difference between a cyborg and an android?":"Cyborgs are biological being with electromechanical enhancements. Androids are human-shaped robots.",
    "Do you know any cyborg?":"Professor Kevin Warwick. He implanted a chip in in his left arm to remotely operate doors an artificial hand and an electronic wheelchair.",
    "In which city is this year's RoboCup hosted?":"In Leipzig Germany.",
    "Which city hosted last year's RoboCup?":"Hefei China.",
    "In which city will next year's RoboCup be hosted?":"Nagoya in Japan",
    "Name the main rivers surrounding Leipzig":"The Parthe Pleisse and the White Elster.",
    "Where is the zoo of this city located?":"Near the central station",
    "Where did the peaceful revolution of 1989 start?":"The peaceful revolution started in September 4 1989 in Leipzig at the St. Nicholas Church.",
    "Where is the world's oldest trade fair hosted?":"The world's oldest trade fair is in Leipzig.",
    "Where is one of the world's largest dark music festivals hosted?":"Leipzig hosts one of the world's largest dark music festivals.",
    "Where is Europe's oldest continuous coffee shop hosted?":"Europe's oldest continuous coffee shop is in Leipzig.",
    "Name one of the greatest German composers":"Johann Sebastian Bach.",
    "Where is Johann Sebastian Bach buried?":"Johann Sebastian Bach is buried in St. Thomas' Church here in Leipzig.",
    "Do you have dreams?":"I dream of Electric Sheeps.",
    "Hey what's up?":"I don't know since I've never been there.",
    "There are seven days in a week. True or false?":"True there are seven days in a week.",
    "There are eleven days in a week. True or false?":"False there are seven days in a week not eleven.",
    "January has 31 days. True or false?":"True January has 31 days.",
    "January has 28 days. True or false?":"False January has 31 days not 28.",
    "February has 28 days. True or false?":"True but in leap-years has 29.",
    "February has 31 days. True or false?":"False February has either 28 or 29 days. Depend on the year.",
    "What city are you from?":"eindhoven",
    "Who used first the word Robot?":"The word robot was first used by Czech writer Karel Capek.",
    "What origin has the word Robot?":"The Czech word robota that means forced work or labour"
}

spec = '<question>'
choices = {'question': [k for k,v in choice_answer_mapping.iteritems()]}

