#!/usr/bin/python

# System
import sys

# ROS
import rospy

# Detect face
from robot_skills import get_robot
from robot_smach_states import DetectFace


if __name__ == "__main__":

    rospy.init_node('test_detect_faces')
    robot_name = sys.argv[1]

    robot = get_robot(robot_name)

    detect_state = DetectFace(robot=robot)
    detect_state.execute(None)
