#!/usr/bin/env python
#
# Copyright (c) 2019, TU/e Robotics, Netherlands
# All rights reserved.

import os

import rospy
from robot_smach_states.util.startup import startup
from challenge_storing_groceries.storing_groceries import setup_statemachine


if __name__ == '__main__':
    challenge_name = os.path.basename(__file__)
    rospy.init_node(challenge_name)
    startup(setup_statemachine, challenge_name=challenge_name)
