#!/usr/bin/python

import sys
import rospy
from robot_skills import get_robot
from challenge_storing_groceries.inspect_shelves import InspectShelves


if __name__ == '__main__':
    rospy.init_node('test_inspect_shelves')

    name = sys.argv[1] if len(sys.argv) > 1 else "amigo"
    robot = get_robot(name=name)

    robot.ed.reset()
    s = InspectShelves(robot)
    result = s.execute(None)
    print result

