#!/usr/bin/python

import rospy
from robot_smach_states.util.startup import startup
from challenge_storing_groceries.manipulate_machine import ManipulateMachine


if __name__ == '__main__':
    rospy.init_node('state_machine')

    startup(ManipulateMachine)
