choice_answer_mapping = {
"What shape is this building" : " UFO",
"Who was beaten by AlphaGo" : " Lee Sedol",
"Which chess grand master was beaten by Deep Blue" : " Gary Kasparov",
"What is the first law of robotics" : "A robot may not injure a human being or through inaction allow a human being to come to harm",
"What is the second law of robotics" : "A robot must obey orders given it by human beings except where such orders would conflict with the First Law",
"What is the third law of robotics" : "A robot must protect its own existence as long as such protection does not conflict with the First or Second Law",
"How many arms do you have" : " I should have two",
"What is this building called" : " Evoluon",
"What city are we in" : " Eindhoven",
"What country are we in" : " Netherlands",
"What continent are we on" : " Europe",
"What planet are we on" : " Earth",
"Who wrote the Laws of robotics" : " Isaac Asimov",
"Which robot was the star of Short Circuit" : " Johny Five",
"Who is the companion of R2D2" : " C-3PO",
"What is the name of the actor that played Commander Data" : " Brent Spiner",
"What is the term for a robot that looks like a human" : " Android",
"Name the two families in Romeo and Juliet" : " Montague & Capulet",
"What are names of Donald Duck's nephews" : " Huey, Dewey and Louie Duck",
"How many liters are in a gallon" : " About 4 but US and imperial gallons are different.",
"What did Alan Turing break" : " The Enigma code.",
"Who coined the term bug in computer programming" : " Grace Hopper",
"What Apollo was the first to land on the moon" : " Apollo 11",
"Who was the first man to step on the moon" : " Neil Armstrong",
"What does Hannibal say in The A-Team when a plan works" : " I love it when a plan comes together",
"Who made an offer that can't be refused" : " Don Corleone in The Godfather",
"What should you never forget in The Hitchhiker's Guide to the Galaxy" : " A towel",
"What is the lightest element" : " Hydrogen",
"Where does the president of the United States live" : " The White House",
"Where does the prime minister of the UK live" : " 10 Downing Street",
"Name a wizard in The Lord of the Rings" : " Gandalf",
"Who is the prime minister of the Netherlands" : " Mark Rutte",
"How many bits are in a byte" : " Eight",
"What is the full name of DNA" : " Deoxyribonucleic acid",
"What is the heavy breathing character of the original Star Wars trilogy" : " Darth Vader",
"Which company makes ASIMO" : " Honda",
"What company makes Big Dog" : " Boston Dynamics",
"Who is the co-pilot of the Millennium Falcon" : " Chewbacca",
"How many people live in the Netherlands" : " About 16.8 million",
"What are the colors of the Dutch flag" : " Red, white and blue.",
"What city is the capital of the Netherlands" : " Amsterdam",
"What countries does the Netherlands have as neighbors" : " Belgium and Germany",
"What city used to be called New Amsterdam" : " New York City",
"Can you name an animal that is a bird but can't fly" : " Penguins",
"What does ROM stand for in computing" : " Read-Only Memory",
"What is DVD an abbreviation of" : " Digital Versatile Disc or Digital Video Disc",
"Who is the original creator on Linux" : " Linus Torvalds",
"What operating system do you run" : " ubuntu baby",
"How many wheels do you have" : " four",
"What is your team name" : " tech united"
}

spec = '<question>'
choices = {'question': [k for k,v in choice_answer_mapping.iteritems()]}

