#!/usr/bin/python

# ROS
import rospy

# TU/e Robotics
from robot_smach_states.util.startup import startup

# Challenge presentation
from challenge_presentation.presentation import PresentationMachine

if __name__ == '__main__':
    rospy.init_node('state_machine')

    startup(PresentationMachine)
