#!/usr/bin/env python

import rospy
import tf
from geometry_msgs.msg import PoseStamped
from robot_skills.world_model_ed import ED
from robot_skills.util.kdl_conversions import FrameStamped, pose_msg_to_kdl_frame


def callback(msg):
    kdl_frame = pose_msg_to_kdl_frame(msg.pose)
    ed.update_entity(entity_id, frame_stamped=FrameStamped(kdl_frame, msg.header.frame_id))


if __name__ == "__main__":
    rospy.init_node("update_ed_entity_pose")
    entity_id = rospy.get_param("~entity_id")
    sub = rospy.Subscriber("update_entity_pose", PoseStamped, callback)
    ed = ED(rospy.get_param("~robot_name"), tf.TransformListener())
    rospy.loginfo("Listening on topic {}".format(sub.name))
    rospy.spin()
