#!/usr/bin/python

import rospy
from challenge_cleanup.cleanup import setup_statemachine
from robot_smach_states.util.startup import startup


if __name__ == "__main__":
    rospy.init_node("challenge_cleanup")
    startup(setup_statemachine)
