#!/usr/bin/env python
import rospy

from robot_smach_states.util import startup
from challenge_find_my_mates.find_my_mates import setup_statemachine

if __name__ == '__main__':
    rospy.init_node('find_my_mates_exec')
    startup(setup_statemachine, challenge_name="find_my_mates")
