#!/usr/bin/env python
import robot_smach_states as states
import robot_smach_states.util.designators as ds
import rospy
import smach
from challenge_find_my_mates.identify_people import IdentifyPeople
from challenge_find_my_mates.inspect_people import InspectPeople
from robot_skills.util.entity import Entity
from robot_smach_states.util import startup

from challenge_find_my_mates.report_people import ReportPeople
from robocup_knowledge import load_knowledge

challenge_knowledge = load_knowledge('challenge_find_my_mates')

STARTING_POINT = challenge_knowledge.starting_point
ROOM_ID = challenge_knowledge.room
SEARCH_POINT = challenge_knowledge.search_point
OPERATOR_POINT = challenge_knowledge.starting_point


def setup_statemachine(robot):
    sm = smach.StateMachine(outcomes=['done', 'failed', 'aborted'])

    found_people_designator = ds.VariableDesignator(resolve_type=[Entity], name='found_people_designator')

    with sm:
        smach.StateMachine.add('START_CHALLENGE_ROBUST', states.StartChallengeRobust(robot, STARTING_POINT),
                               transitions={'done': 'GO_TO_SEARCH_POSE',
                                            'preempted': 'aborted',
                                            'error': 'GO_TO_SEARCH_POSE'})

        smach.StateMachine.add('SAY_START',
                               states.Say(robot, "Finding your mates, lalalala!"),
                               transitions={'spoken': 'GO_TO_SEARCH_POSE'})

        smach.StateMachine.add('GO_TO_SEARCH_POSE',
                               states.NavigateToWaypoint(robot, ds.EntityByIdDesignator(robot, id=SEARCH_POINT),
                                                         radius=0.5),
                               transitions={'arrived': 'LOCATE_PEOPLE',
                                            'goal_not_defined': 'failed',
                                            'unreachable': 'WAIT_SEARCH_POSE'})

        smach.StateMachine.add('WAIT_SEARCH_POSE',
                               states.WaitTime(robot, 5),
                               transitions={'preempted': 'preempted',
                                            'waited': 'GO_TO_SEARCH_POSE'})

        # locate all four people
        smach.StateMachine.add('LOCATE_PEOPLE',
                               LocatePeople(robot,
                                            found_people_designator=found_people_designator.writeable,
                                            room_id=ROOM_ID),
                                            attempts=2),
                               transitions={'done': 'IDENTIFY_PEOPLE',
                                            'aborted': 'done',
                                            'failed': 'LOCATE_PEOPLE'})

        # drive past all four people and fill their description
        smach.StateMachine.add('IDENTIFY_PEOPLE',
                               IdentifyPeople(robot,
                                              found_people_designator=found_people_designator,
                                              identified_people_designator=found_people_designator.writeable),
                               transitions={'done': 'GO_BACK_TO_OPERATOR',
                                            'aborted': 'done',
                                            'failed': 'GO_BACK_TO_OPERATOR'})

        # drive back to the operator to describe the mates
        smach.StateMachine.add('GO_BACK_TO_OPERATOR',
                               states.NavigateToWaypoint(
                                   robot, ds.EntityByIdDesignator(robot, id=OPERATOR_POINT),
                                   radius=0.7, look_at_designator=ds.EntityByIdDesignator(robot, id=OPERATOR_POINT)),
                               transitions={'arrived': 'REPORT_PEOPLE',
                                            'goal_not_defined': 'REPORT_PEOPLE',
                                            'unreachable': 'WAIT_GO_BACK'})

        smach.StateMachine.add('WAIT_GO_BACK',
                               states.WaitTime(robot, 5),
                               transitions={'preempted': 'preempted',
                                            'waited': 'GO_BACK_TO_OPERATOR'})

        # check how to uniquely define them
        smach.StateMachine.add('REPORT_PEOPLE', ReportPeople(robot, identified_people_designator),
                               transitions={'done': 'done',
                                            'aborted': 'done',
                                            'failed': 'failed'})

    return sm


if __name__ == '__main__':
    rospy.init_node('find_my_mates_exec')
    startup(setup_statemachine, challenge_name="find_my_mates")
