#! /usr/bin/env python

import rospy
from challenge_receptionist.receptionist import ChallengeReceptionist
from robot_smach_states.util.startup import startup

if __name__ == "__main__":
    rospy.init_node("state_machine")

    startup(ChallengeReceptionist)
