#!/usr/bin/python

import rospy
from robot_smach_states.util.startup import startup
from challenge_serving_drinks.serving_drinks import ServingDrinks


if __name__ == '__main__':
    rospy.init_node('state_machine')

    startup(ServingDrinks)
