#!/usr/bin/python

import rospy
from robot_smach_states.util.startup import startup
import challenge_restaurant.restaurant

if __name__ == "__main__":

    rospy.init_node('state_machine')

    startup(challenge_restaurant.restaurant.Restaurant)
