#!/usr/bin/env python
import sys
import os
import rospy
import subprocess as sub
import roslib; roslib.load_manifest('challenge_demo')
import rospkg
from pein_msgs.msg import ODM

def oduCB(data):
    for image in data.object_images:
	if len(image.object_evidence) > 0:
	    import pdb; pdb.set_trace()
	#obj = max(image.object_evidence.iterkeys(), key=(lamda key: stats[key]))
            #string  object_name
            #string  category
            #float64 probability
            #rospy.loginfo('name: %s', hypothesis.object_name)

rospy.init_node("pub_objects_external_kinect", anonymous=True)

sub = rospy.Subscriber("/external_kinect/odu_finder/output", ODM, oduCB)

rospy.spin()
