#!/usr/bin/env python
import sys
import os
import rospy
import subprocess as sub
import roslib; roslib.load_manifest('challenge_demo')
import rospkg
from pein_msgs.msg import ODM

def oduCB(data):
    for image in data.object_images:
        print image.object_evidence

rospy.init_node("pub_objects_external_kinect", anonymous=True)

sub = rospy.Subscriber("/external_kinect/odu_finder/output", ODM, oduCB)

rospy.spin()
