#!/usr/bin/env python
import sys
import os
import rospy
import subprocess as sub
import roslib; roslib.load_manifest('challenge_demo')
import rospkg
from pein_srvs.srv import StartStopWithROI
from pein_msgs.msg import ROI

rospy.init_node("start_external_object_segmentation", anonymous=True)

print "Trying to toggle Object Detection"

roi = ROI()
roi.x = 0
roi.y = 0
roi.z = 1
roi.length_x = 1
roi.length_y = 1
roi.length_z = 1
roi.frame = '/external_kinect/openni_rgb_optical_frame'

try:
    rospy.wait_for_service("/external_kinect/object_segmentation/roi_srv_input")
    start_roi = rospy.ServiceProxy("/external_kinect/object_segmentation/roi_srv_input", StartStopWithROI)
    response = start_roi(True,roi)
except (rospy.ServiceException, rospy.ROSException), e:
    print(">> Set ROI service not available: {0}".format(e))

print ">> Toggled Object Detection"

