#! /usr/bin/env python3

import rospy
from robot_smach_states.util.startup import startup
from challenge_stickler_for_rules.stickler_for_rules import SticklerForRules

if __name__ == "__main__":

    rospy.init_node('stickler_for_rules')

    startup(SticklerForRules)
