#!/usr/bin/env python
#
# Copyright (c) 2019, TU/e Robotics, Netherlands
# All rights reserved.
#
# \author Rein Appeldoorn

from __future__ import print_function
import os
import rospy

from challenge_hand_me_that.hand_me_that import HandMeThat
from robot_smach_states.util.startup import startup


if __name__ == '__main__':
    challenge_name = os.path.basename(__file__)
    rospy.init_node(challenge_name)
    startup(HandMeThat)
