#! /usr/bin/env python

import rospy

from challenge_rips.rips import setup_statemachine
from robot_smach_states.util.startup import startup

if __name__ == '__main__':
    rospy.init_node('rips_exec')

    startup(setup_statemachine, challenge_name="rips")
