#!/usr/bin/python

import rospy
from challenge_final.final import ChallengeFinal
from robot_smach_states.util.startup import startup

if __name__ == "__main__":
    rospy.init_node("state_machine")

    startup(ChallengeFinal)
