#!/usr/bin/python3

import rospy

from challenge_final.final import Final
from robot_smach_states.util.startup import startup

if __name__ == '__main__':
    rospy.init_node('state_machine_rwc2022')

    startup(Final)
