#!/usr/bin/python

# System
import rospy

# TU/e Robotics
from robot_smach_states.util.startup import startup

# Challenge where is this
from challenge_where_is_this.where_is_this import WhereIsThis


if __name__ == '__main__':
    rospy.init_node('where_is_this')

    startup(WhereIsThis)
